# Generated by Django 5.0.1 on 2024-08-07 07:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact_model",
            name="message",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
