# Generated by Django 5.0.1 on 2024-08-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0002_alter_contact_model_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nm", models.CharField(max_length=40)),
                ("em", models.EmailField(max_length=254)),
                ("pw", models.CharField(max_length=40)),
            ],
        ),
    ]
