# Generated by Django 5.0.1 on 2024-08-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0003_user_register"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_register",
            old_name="em",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="user_register",
            old_name="nm",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="user_register",
            old_name="pw",
            new_name="password",
        ),
    ]
