# Generated by Django 5.0.1 on 2024-08-07 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0004_rename_em_user_register_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_register",
            name="c_password",
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
