# Generated by Django 5.0.1 on 2024-08-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0005_user_register_c_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="user_register",
        ),
    ]
