# Generated by Django 5.0.1 on 2024-08-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0007_user_register"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_register",
            name="c_password",
        ),
        migrations.AddField(
            model_name="user_register",
            name="address",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_register",
            name="dob",
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_register",
            name="phone",
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_register",
            name="pincode",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
