# Generated by Django 5.0.1 on 2024-08-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0008_remove_user_register_c_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_register",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user_register",
            name="dob",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="user_register",
            name="phone",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="user_register",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
