# Generated by Django 5.0.1 on 2024-08-21 08:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0010_user_register_country_user_register_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="university",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("establish", models.CharField(max_length=50)),
                ("director", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, null=True, upload_to="data")),
                ("location", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("des", ckeditor.fields.RichTextField()),
                ("video", models.FileField(upload_to="")),
            ],
        ),
    ]
