# Generated by Django 5.0.1 on 2024-08-21 14:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0011_university_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="agriculture_video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("video", models.FileField(blank=True, null=True, upload_to="data")),
            ],
        ),
        migrations.CreateModel(
            name="crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="data")),
                ("desc", ckeditor.fields.RichTextField()),
                ("video", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="farmers_call_centre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("details", ckeditor.fields.RichTextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="data")),
            ],
        ),
        migrations.CreateModel(
            name="farmers_scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("desc", ckeditor.fields.RichTextField()),
                ("pdf", models.FileField(blank=True, null=True, upload_to="data")),
            ],
        ),
        migrations.CreateModel(
            name="indian_agriculture_university",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("desc", ckeditor.fields.RichTextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="data")),
                ("city", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="latest_technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, null=True, upload_to="data")),
                ("desc", ckeditor.fields.RichTextField()),
            ],
        ),
    ]
