# Generated by Django 5.0.1 on 2024-08-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0012_agriculture_video_crop_farmers_call_centre_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="university",
        ),
        migrations.RenameField(
            model_name="indian_agriculture_university",
            old_name="city",
            new_name="director",
        ),
        migrations.AddField(
            model_name="indian_agriculture_university",
            name="establish",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="indian_agriculture_university",
            name="location",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
