# Generated by Django 5.0.1 on 2024-08-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0013_delete_university_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="video",
        ),
    ]
