# Generated by Django 5.0.1 on 2024-08-24 12:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0014_delete_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("des", ckeditor.fields.RichTextField()),
                ("video", models.FileField(upload_to="")),
            ],
        ),
        migrations.RemoveField(
            model_name="farmers_scheme",
            name="pdf",
        ),
        migrations.AddField(
            model_name="farmers_scheme",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="data"),
        ),
    ]
