# Generated by Django 5.0.1 on 2024-08-26 11:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0015_video_remove_farmers_scheme_pdf_farmers_scheme_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="agriculture_video",
        ),
        migrations.AddField(
            model_name="farmers_scheme",
            name="link",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="indian_agriculture_university",
            name="details",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
