# Generated by Django 5.0.1 on 2024-08-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0016_delete_agriculture_video_farmers_scheme_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_register",
            name="profileimg",
            field=models.ImageField(blank=True, null=True, upload_to="data"),
        ),
    ]
