# Generated by Django 5.0.1 on 2024-08-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0017_user_register_profileimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_register",
            name="profileimg",
            field=models.ImageField(blank=True, null=True, upload_to="profile"),
        ),
    ]
