# Generated by Django 5.0.1 on 2024-08-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0018_alter_user_register_profileimg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indian_agriculture_university",
            name="details",
        ),
    ]
