# Generated by Django 5.0.1 on 2024-08-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0020_state_agriculturedata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgricultureData",
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
