# Generated by Django 5.0.1 on 2024-09-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0022_state_agriculturedata"),
    ]

    operations = [
        migrations.AddField(
            model_name="agriculturedata",
            name="crop_images",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
