# Generated by Django 5.0.1 on 2024-09-03 05:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0023_agriculturedata_crop_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agriculturedata",
            name="crop_images",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
