# Generated by Django 5.0.1 on 2024-09-03 06:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0024_alter_agriculturedata_crop_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="agriculturedata",
            name="flower_images",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agriculturedata",
            name="fruit_images",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agriculturedata",
            name="vegetable_images",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
