# Generated by Django 5.0.1 on 2024-09-05 06:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0025_agriculturedata_flower_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agriculturedata",
            name="crop_images",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agriculturedata",
            name="flower_images",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agriculturedata",
            name="fruit_images",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agriculturedata",
            name="vegetable_images",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
