# Generated by Django 5.0.1 on 2024-11-02 11:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0026_alter_agriculturedata_crop_images_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", ckeditor.fields.RichTextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="data")),
                ("desc", ckeditor.fields.RichTextField()),
                ("date", ckeditor.fields.RichTextField()),
                ("by", ckeditor.fields.RichTextField()),
            ],
        ),
    ]
