# Generated by Django 5.0.1 on 2024-11-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0027_blogs"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="blogs",
            new_name="Blog",
        ),
    ]
