# Generated by Django 5.0.1 on 2024-11-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AgroTech", "0028_rename_blogs_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="by",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="blog",
            name="date",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
